### ISSUE TITLE
HIP vector types do not link properly with a combination of gcc and hcc 

### ISSUE THREAD

**Issue by jglaser** [ROCm-Developer-Tools/HIP#1675]
With the development version of HIP (3a7eb694f508517b3389ed8a9295bf41f8d16685), I get linker errors in a project which mixes gcc-compiled objects with hipcc-compiled device methods. The reason is a change in hcc_detail/hip_vector_types.h, which defines e.g. double4 differently with gcc and clang. The linker doesn't recognize they're the same anymore. Reverting back to roc 2.9.

**Comment by jglaser** [comment]
The changes introduced in 4a635ad are really problematic.  For instance, the definition of the `Scalar_accessor` functions as members of the vector types introduces problems with template argument deduction,  in particular when e.g. `double4` members are passed to atomicMax functions or other templates (like in serialization libraries). These functions expect e.g. the double member `.x` to be of data type double, but now it is of data type `hip_impl::Scalar_accessor`. Moreover, some operators like bitwise shift which are not present in CUDA are introduced here and can cause compilation errors. Could these changes be reverted?
