### ISSUE TITLE
Accessing global device variable accessible form multiple compilations units

### ISSUE THREAD

**Issue by masterleinad** [ROCm-Developer-Tools/HIP#2109]
In our application, we want to be able to use a global device variable in multiple compilation units without using relocatable device code. In this case, we expect that the global device variable is replicated for every compilation unit and not shared. The idea is to have a global (host) variable and copy its contents in every compile unit it is used.
A minimal code looks as follows:
Locks.hpp:
```c++
#ifndef LOCKS_HPP
#define LOCKS_HPP

#include <cstdint>
#include <hip/hip_runtime.h>

struct HIPLockArrays {
  std::int32_t* atomic;
  std::int32_t* scratch;
  std::int32_t n;
};

extern HIPLockArrays g_host_hip_lock_arrays;

namespace Impl {
void initialize_host_hip_lock_arrays();
}  // namespace Impl

__device__ HIPLockArrays g_device_hip_lock_arrays;

#define IMPL_HIP_SPACE_ATOMIC_MASK 0x1FFFF

#endif /* #ifndef LOCKS_HPP */
```
Locks.cpp (some boiler plate for printing error messages, `initialize_host_hip_lock_arrays` is the interesting part)
```c++
#include "Locks.hpp"

#include <hip/hip_runtime.h>

#include <iostream>

namespace Impl {

void hip_internal_error_throw(hipError_t e, const char *name, const char *file,
                              const int line) {
  std::ostringstream out;
  out << name << " error( " << hipGetErrorName(e)
      << "): " << hipGetErrorString(e);
  if (file) {
    out << " " << file << ":" << line;
  }
  throw std::runtime_error(out.str());
}


inline void hip_internal_safe_call(hipError_t e, const char* name,
                                   const char* file = NULL,
                                   const int line   = 0) {
  if (hipSuccess != e) {
    hip_internal_error_throw(e, name, file, line);
  }
}

}  // namespace Impl

#define HIP_SAFE_CALL(call) \
  Impl::hip_internal_safe_call(call, #call, __FILE__, __LINE__)

namespace Impl {

HIPLockArrays g_host_hip_lock_arrays = {nullptr, nullptr, 0};

void initialize_host_hip_lock_arrays() {
  constexpr int concurrency = 100;

  if (g_host_hip_lock_arrays.atomic != nullptr) return;
  HIP_SAFE_CALL(hipMalloc(
      &g_host_hip_lock_arrays.atomic,
      sizeof(std::int32_t) * (IMPL_HIP_SPACE_ATOMIC_MASK + 1)));
  HIP_SAFE_CALL(hipMalloc(
      &g_host_hip_lock_arrays.scratch,
      sizeof(std::int32_t) * concurrency));

  g_host_hip_lock_arrays.n = concurrency;

  {
    size_t size = 0;
    hipGetSymbolSize(&size, g_device_hip_lock_arrays);
    HIP_SAFE_CALL(hipDeviceSynchronize());
    std::cout << "symbol size " << size << std::endl;
     void* address = nullptr;
    hipGetSymbolAddress(&address, HIP_SYMBOL(g_device_hip_lock_arrays));
    HIP_SAFE_CALL(hipDeviceSynchronize());
    std::cout << "symbol address " << address << std::endl;
  }

    HIP_SAFE_CALL(hipMemcpyToSymbol(HIP_SYMBOL(g_device_hip_lock_arrays),
                                    &g_host_hip_lock_arrays,
                                    sizeof(HIPLockArrays)));
}
}  // namespace Impl
```
Instance.cpp
```c++
#include "Locks.hpp"

namespace Impl
{
  void initialize_host_hip_lock_arrays();
}

int main()
{
  Impl::initialize_host_hip_lock_arrays();
}
```
Basically, we want `Impl::initialize::host_hip_lock_arrays` to initialize `g_host_hip_lock_arrays`,`g_device_hip_lock_arrays` and in particular, `g_device_hip_lock_arrays`.
Compiling these files using HIP 3.5 and running the resulting executable via
```
hipcc -o shared Locks.cpp Instance.cpp && ./shared
```
gives
```
symbol size 0
symbol address 0
terminate called after throwing an instance of 'std::runtime_error'
  what():  hipMemcpyToSymbol(HIP_SYMBOL(g_device_hip_lock_arrays), &g_host_hip_lock_arrays, sizeof(HIPLockArrays)) error( hipErrorInvalidSymbol): hipErrorInvalidSymbol Locks.cpp:64
Aborted (core dumped)
```
though. Essentially, we can't even get the address of `g_device_hip_lock_arrays`.
The issue is resolved if we either merge `Locks.cpp` `Instance.cpp` together and, thus, creating a single compilation or avoid including `Locks.hpp` in `Instance.cpp`. This results in the expected output
```
symbol size 24
symbol address 0x7f1190c83000
```
 Of course, neither of these workarounds is a suitable solution. It appears that the mere existence of `g_device_hip_lock_arrays` in multiple compilation units makes all of them invalid.
The issue might be related to #1920.

**Comment by arghdos** [comment]
@masterleinad -- I can reproduce this locally.  One solution I've found is, in `locks.hpp`, make the `g_device_hip_lock_arrays` definition extern.

```
extern __device__ HIPLockArrays g_device_hip_lock_arrays;
```

Then insert a definition inside of `locks.cpp`:

```
HIPLockArrays g_host_hip_lock_arrays = {nullptr, nullptr, 0};
__device__ HIPLockArrays g_device_hip_lock_arrays;
```

When I compile:

```
$hipcc -O3 -fgpu-rdc -c locks_multi.hip -o locks_multi.o
$hipcc -O3 -fgpu-rdc -c instance.hip -o instance.o
$hipcc -O3 -fgpu-rdc instance.o locks_multi.o -o a.out
$./a.out
symbol size 24
symbol address 0x7f15e5483000
```

**Comment by arghdos** [comment]
I think needing `extern` is actually expected though... right? If we tried to do the same thing with `g_host_hip_lock_arrays`, i.e., no-extern, include into multiple cpp's, we'd get a linking error.

**Comment by masterleinad** [comment]
The point here is to make it work without relocatable device code.
Yes, we would get a linker error for `g_host_hip_lock_arrays` but global device symbols are bound to a compilation unit in `CUDA` and thus it works with nvcc.

**Comment by arghdos** [comment]
oh damn.. I completely misread, apologies.

**Comment by arghdos** [comment]
... interestingly, the same modifications seem to be working w/ `-fno-gpu-rdc`:

```
$ hipcc -fno-gpu-rdc -c Locks.cpp -o Locks.o
$ hipcc -fno-gpu-rdc -c Instance.cpp -o Instance.o       
$ hipcc -fno-gpu-rdc Locks.o Instance.o -o a.out
clang-11: warning: argument unused during compilation: '-fno-gpu-rdc' [-Wunused-command-line-argument]
$ ./a.out 
symbol size 0
symbol address 0
terminate called after throwing an instance of 'std::runtime_error'
  what():  hipMemcpyToSymbol(HIP_SYMBOL(g_device_hip_lock_arrays), &g_host_hip_lock_arrays, sizeof(HIPLockArrays)) error( hipErrorInvalidSymbol): hipErrorInvalidSymbol Locks.cpp:64
Aborted (core dumped)
```

```
$ diff Locks_extern.cpp Locks.cpp 
37d36
< __device__ HIPLockArrays g_device_hip_lock_arrays;
$ diff Locks_extern.hpp Locks.hpp 
19c19
< extern __device__ HIPLockArrays g_device_hip_lock_arrays;
---
> __device__ HIPLockArrays g_device_hip_lock_arrays;
$ hipcc -fno-gpu-rdc -c Locks_extern.cpp -o Locks.o
$ hipcc -fno-gpu-rdc -c Instance.cpp -o Instance.o
$ hipcc -fno-gpu-rdc Locks.o Instance.o -o a.out
$ ./a.out 
symbol size 24
symbol address 0x7fd99de83018
```

which I have to admit... I'm pretty surprised about?

**Comment by masterleinad** [comment]
Hmm... With these changes I get
```
# hipcc -fno-gpu-rdc -o shared Locks.cpp Instance.cpp && ./shared
/tmp/Instance-af9053.o: In function `main':
Instance.cpp:(.text+0x16): undefined reference to `Impl::g_device_hip_lock_arrays'
Instance.cpp:(.text+0xa5): undefined reference to `Impl::g_device_hip_lock_arrays'
```
and if I try to compile two files separately
```
$ hipcc -fno-gpu-rdc -o Locks.o -c Locks.cpp
$ hipcc -fno-gpu-rdc -o Instance.o -c Instance.cpp
$ hipcc -fno-gpu-rdc Instance.o Locks.o -o a.out
clang-11: warning: argument unused during compilation: '-fno-gpu-rdc' [-Wunused-command-line-argument]
Instance.o: In function `main':
Instance.cpp:(.text+0x16): undefined reference to `Impl::g_device_hip_lock_arrays'
Instance.cpp:(.text+0xa5): undefined reference to `Impl::g_device_hip_lock_arrays'
```
and
```
# nm Instance.o  | grep "g_"
                 U _ZN4Impl22g_host_hip_lock_arraysE
                 U _ZN4Impl24g_device_hip_lock_arraysE
# nm Locks.o  | grep "g_"
0000000000000008 B _ZN4Impl22g_host_hip_lock_arraysE
0000000000000020 b _ZN4Impl24g_device_hip_lock_arraysE
```
as soon as I add
```
  {
    size_t size = 0;
    hipGetSymbolSize(&size, Impl::g_device_hip_lock_arrays);
    hipDeviceSynchronize();
    std::cout << "symbol size " << size << std::endl;
     void* address = nullptr;
    hipGetSymbolAddress(&address, HIP_SYMBOL(Impl::g_device_hip_lock_arrays));
    hipDeviceSynchronize();
    std::cout << "symbol address " << address << std::endl;
  }
```
to `Instance.cpp`.

**Comment by arghdos** [comment]
Following up on email.

**Comment by masterleinad** [comment]
The initial code seems to work with rocm-3.8.

**Comment by masterleinad** [comment]
It also works with rocm-4.1.
