### ISSUE TITLE
Hipcc unable to compile simple program

### ISSUE THREAD

**Issue by Ledarium** [ROCm-Developer-Tools/HIP#2368]
I am unable to compile this code `int main() { return 0; }`:
```
╰─ hipcc -v test.cpp
clang version 13.0.0 (https://aur.archlinux.org/llvm-amdgpu.git 3bd935c95e7353ed2cbb09dbab31e4ed73e8a45a)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.3.0
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0
Selected GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
Found CUDA installation: /opt/cuda, version 11.0
Found HIP installation: /opt/rocm, version 4.3.21346-3ac9bda
 "/opt/rocm/llvm/bin/clang-offload-bundler" -unbundle -type=a -inputs=/opt/rocm/llvm/bin/../lib/clang/13.0.0/lib/linux/libclang_rt.builtins-x86_64.a -targets=hip-amdgcn-amd-amdhsa-gfx803 -outputs=/tmp/libbc-clang_rt.builtins-x86_64-amdgcn-gfx803-d5fd78.a
 "/opt/rocm/llvm/bin/clang-13" -cc1 -mllvm --amdhsa-code-object-version=4 -triple amdgcn-amd-amdhsa -aux-triple x86_64-pc-linux-gnu -emit-obj --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.cpp -mrelocation-model pic -pic-level 1 -fhalf-no-semantic-interposition -mframe-pointer=none -fdenormal-fp-math-f32=preserve-sign,preserve-sign -fno-rounding-math -aux-target-cpu x86-64 -mlink-builtin-bitcode /tmp/libbc-clang_rt.builtins-x86_64-amdgcn-gfx803-d5fd78.a -fcuda-is-device -mllvm -amdgpu-internalize-symbols -fcuda-allow-variadic-functions -fvisibility hidden -fapply-global-visibility-to-externs -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/hip.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/ocml.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/ockl.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_daz_opt_on.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_unsafe_math_off.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_finite_only_off.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_correctly_rounded_sqrt_on.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_wavefrontsize64_on.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_isa_version_803.bc -target-cpu gfx803 -fno-split-dwarf-inlining -debugger-tuning=gdb -v -resource-dir /opt/rocm/llvm/lib/clang/13.0.0 -internal-isystem /opt/rocm/llvm/lib/clang/13.0.0/include/cuda_wrappers -internal-isystem /opt/rocm/include -include __clang_hip_runtime_wrapper.h -isystem /opt/rocm/llvm/lib/clang/13.0.0/include/.. -isystem /opt/rocm/hsa/include -isystem /opt/rocm/hip/include -internal-isystem /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0 -internal-isystem /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/x86_64-pc-linux-gnu -internal-isystem /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/backward -internal-isystem /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0 -internal-isystem /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/x86_64-pc-linux-gnu -internal-isystem /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/backward -internal-isystem /usr/local/include -internal-isystem /opt/rocm/llvm/lib/clang/13.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -internal-isystem /usr/local/include -internal-isystem /opt/rocm/llvm/lib/clang/13.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -std=c++11 -fdeprecated-macro -fno-autolink -fdebug-compilation-dir=/home/dmaylarov/bin/tryrust -ferror-limit 19 -fhip-new-launch-api -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -vectorize-loops -vectorize-slp -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -cuid=1dbb4705558bb95e -fcuda-allow-variadic-functions -munsafe-fp-atomics -faddrsig -o /tmp/test-gfx803-286619.o -x hip test.cpp
clang -cc1 version 13.0.0 based upon LLVM 13.0.0git default target x86_64-pc-linux-gnu
ignoring nonexistent directory "/include"
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0"
ignoring duplicate directory "/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/x86_64-pc-linux-gnu"
ignoring duplicate directory "/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/backward"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/opt/rocm/llvm/lib/clang/13.0.0/include"
ignoring duplicate directory "/usr/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/opt/rocm/llvm/lib/clang/13.0.0/include"
ignoring duplicate directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/rocm/llvm/lib/clang/13.0.0/include/..
 /opt/rocm/hsa/include
 /opt/rocm/hip/include
 /opt/rocm/llvm/lib/clang/13.0.0/include/cuda_wrappers
 /opt/rocm/include
 /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0
 /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/x86_64-pc-linux-gnu
 /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/backward
 /usr/local/include
 /opt/rocm/llvm/lib/clang/13.0.0/include
 /usr/include
End of search list.
In file included from <built-in>:1:
In file included from /opt/rocm/hip/include/__clang_hip_runtime_wrapper.h:67:
/opt/rocm/hip/include/__clang_hip_math.h:90:1: error: unknown type name 'uint64_t'
uint64_t __make_mantissa_base8(const char *__tagp) {
^
/opt/rocm/hip/include/__clang_hip_math.h:91:3: error: unknown type name 'uint64_t'
  uint64_t __r = 0;
  ^
/opt/rocm/hip/include/__clang_hip_math.h:107:1: error: unknown type name 'uint64_t'
uint64_t __make_mantissa_base10(const char *__tagp) {
^
/opt/rocm/hip/include/__clang_hip_math.h:108:3: error: unknown type name 'uint64_t'
  uint64_t __r = 0;
  ^
/opt/rocm/hip/include/__clang_hip_math.h:124:1: error: unknown type name 'uint64_t'
uint64_t __make_mantissa_base16(const char *__tagp) {
^
/opt/rocm/hip/include/__clang_hip_math.h:125:3: error: unknown type name 'uint64_t'
  uint64_t __r = 0;
  ^
/opt/rocm/hip/include/__clang_hip_math.h:145:1: error: unknown type name 'uint64_t'
uint64_t __make_mantissa(const char *__tagp) {
^
/opt/rocm/hip/include/__clang_hip_math.h:978:7: error: unknown type name 'uint64_t'
      uint64_t mantissa : 51;
      ^
/opt/rocm/hip/include/__clang_hip_math.h:979:7: error: unknown type name 'uint32_t'
      uint32_t quiet : 1;
      ^
/opt/rocm/hip/include/__clang_hip_math.h:980:7: error: unknown type name 'uint32_t'
      uint32_t exponent : 11;
      ^
/opt/rocm/hip/include/__clang_hip_math.h:981:7: error: unknown type name 'uint32_t'
      uint32_t sign : 1;
      ^
In file included from <built-in>:1:
In file included from /opt/rocm/hip/include/__clang_hip_runtime_wrapper.h:75:
In file included from /opt/rocm/llvm/lib/clang/13.0.0/include/cuda_wrappers/complex:35:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/stdexcept:39:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/string:40:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/char_traits.h:699:
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/cstdint:52:11: error: no member named 'int_fast8_t' in the global namespace
  using ::int_fast8_t;
        ~~^
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/cstdint:53:11: error: no member named 'int_fast16_t' in the global namespace; did you mean '__int_least16_t'?
  using ::int_fast16_t;
        ~~^
/usr/include/bits/types.h:54:19: note: '__int_least16_t' declared here
typedef __int16_t __int_least16_t;
                  ^
In file included from <built-in>:1:
In file included from /opt/rocm/hip/include/__clang_hip_runtime_wrapper.h:75:
In file included from /opt/rocm/llvm/lib/clang/13.0.0/include/cuda_wrappers/complex:35:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/stdexcept:39:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/string:40:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/char_traits.h:699:
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/cstdint:54:11: error: no member named 'int_fast32_t' in the global namespace; did you mean '__int_least32_t'?
  using ::int_fast32_t;
        ~~^
/usr/include/bits/types.h:56:19: note: '__int_least32_t' declared here
typedef __int32_t __int_least32_t;
                  ^
In file included from <built-in>:1:
In file included from /opt/rocm/hip/include/__clang_hip_runtime_wrapper.h:75:
In file included from /opt/rocm/llvm/lib/clang/13.0.0/include/cuda_wrappers/complex:35:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/stdexcept:39:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/string:40:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/char_traits.h:699:
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/cstdint:55:11: error: no member named 'int_fast64_t' in the global namespace; did you mean '__int_least64_t'?
  using ::int_fast64_t;
        ~~^
/usr/include/bits/types.h:58:19: note: '__int_least64_t' declared here
typedef __int64_t __int_least64_t;
                  ^
In file included from <built-in>:1:
In file included from /opt/rocm/hip/include/__clang_hip_runtime_wrapper.h:75:
In file included from /opt/rocm/llvm/lib/clang/13.0.0/include/cuda_wrappers/complex:35:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/stdexcept:39:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/string:40:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/char_traits.h:699:
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/cstdint:57:11: error: no member named 'int_least8_t' in the global namespace; did you mean '__int_least8_t'?
  using ::int_least8_t;
        ~~^
/usr/include/bits/types.h:52:18: note: '__int_least8_t' declared here
typedef __int8_t __int_least8_t;
                 ^
In file included from <built-in>:1:
In file included from /opt/rocm/hip/include/__clang_hip_runtime_wrapper.h:75:
In file included from /opt/rocm/llvm/lib/clang/13.0.0/include/cuda_wrappers/complex:35:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/stdexcept:39:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/string:40:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/char_traits.h:699:
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/cstdint:58:11: error: no member named 'int_least16_t' in the global namespace; did you mean '__int_least16_t'?
  using ::int_least16_t;
        ~~^
/usr/include/bits/types.h:54:19: note: '__int_least16_t' declared here
typedef __int16_t __int_least16_t;
                  ^
In file included from <built-in>:1:
In file included from /opt/rocm/hip/include/__clang_hip_runtime_wrapper.h:75:
In file included from /opt/rocm/llvm/lib/clang/13.0.0/include/cuda_wrappers/complex:35:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/stdexcept:39:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/string:40:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/char_traits.h:699:
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/cstdint:59:11: error: no member named 'int_least32_t' in the global namespace; did you mean '__int_least32_t'?
  using ::int_least32_t;
        ~~^
/usr/include/bits/types.h:56:19: note: '__int_least32_t' declared here
typedef __int32_t __int_least32_t;
                  ^
In file included from <built-in>:1:
In file included from /opt/rocm/hip/include/__clang_hip_runtime_wrapper.h:75:
In file included from /opt/rocm/llvm/lib/clang/13.0.0/include/cuda_wrappers/complex:35:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/stdexcept:39:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/string:40:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/char_traits.h:699:
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/cstdint:60:11: error: no member named 'int_least64_t' in the global namespace; did you mean '__int_least64_t'?
  using ::int_least64_t;
        ~~^
/usr/include/bits/types.h:58:19: note: '__int_least64_t' declared here
typedef __int64_t __int_least64_t;
                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated when compiling for gfx803.
```
hipconfig --full
```
HIP version  : 4.3.21346-3ac9bda

== hipconfig
HIP_PATH     : /opt/rocm/hip
ROCM_PATH    : /opt/rocm
HIP_COMPILER : clang
HIP_PLATFORM : amd
HIP_RUNTIME  : rocclr
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__= -D__HIP_PLATFORM_AMD__= -I"/opt/rocm/hip/include" -I"/opt/rocm/llvm/bin/../lib/clang/13.0.0" -I/opt/rocm/hsa/include

== hip-clang
HSA_PATH         : /opt/rocm/hsa
HIP_CLANG_PATH   : /opt/rocm/llvm/bin
clang version 13.0.0 (https://aur.archlinux.org/llvm-amdgpu.git 3bd935c95e7353ed2cbb09dbab31e4ed73e8a45a)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
LLVM (http://llvm.org/):
  LLVM version 13.0.0git
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: znver1

  Registered Targets:
    amdgcn - AMD GCN GPUs
    r600   - AMD GPUs HD2XXX-HD6XXX
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
hip-clang-cxxflags :  -std=c++11 -isystem "/opt/rocm/llvm/lib/clang/13.0.0/include/.." -isystem /opt/rocm/hsa/include -isystem "/opt/rocm/hip/include" -O3
hip-clang-ldflags  : --driver-mode=g++ -L"/opt/rocm/hip/lib" -O3 -lgcc_s -lgcc -lpthread -lm -lrt

=== Environment Variables
PATH=/usr/lib/ccache:/home/username/.pyenv/bin:HOME/.local/bin:/usr/local/bin:/usr/lib/ccache:/home/username/.local/bin:/usr/lib/ccache:/home/username/.pyenv/bin:HOME/.local/bin:/usr/local/bin:/home/username/.local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/opt/android-sdk/platform-tools:/opt/cuda/bin:/opt/cuda/integration/nsight-compute:/opt/cuda/integration/nsight-systems:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/username/.fzf/bin:/opt/android-sdk/platform-tools:/opt/cuda/bin:/opt/cuda/integration/nsight-compute:/opt/cuda/integration/nsight-systems:/usr/lib/jvm/default/bin
CUDA_PATH=/opt/cuda

== Linux Kernel
Hostname     : dota
Linux dota 5.10.61-1-MANJARO #1 SMP PREEMPT Thu Aug 26 20:36:54 UTC 2021 x86_64 GNU/Linux
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        21.1.3
Codename:       Pahvo
```

**Comment by Ledarium** [comment]
I have also tried specifying gcc 10 version:
```
╰─ hipcc -v --gcc-toolchain=/usr/lib64/gcc/x86_64-pc-linux-gnu/10.3.0/include test.cpp
clang version 13.0.0 (https://aur.archlinux.org/llvm-amdgpu.git 3bd935c95e7353ed2cbb09dbab31e4ed73e8a45a)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
Found CUDA installation: /opt/cuda, version 11.0
Found HIP installation: /opt/rocm, version 4.3.21346-3ac9bda
 "/opt/rocm/llvm/bin/clang-offload-bundler" -unbundle -type=a -inputs=/opt/rocm/llvm/bin/../lib/clang/13.0.0/lib/linux/libclang_rt.builtins-x86_64.a -targets=hip-amdgcn-amd-amdhsa-gfx803 -outputs=/tmp/libbc-clang_rt.builtins-x86_64-amdgcn-gfx803-0aa211.a
 "/opt/rocm/llvm/bin/clang-13" -cc1 -mllvm --amdhsa-code-object-version=4 -triple amdgcn-amd-amdhsa -aux-triple x86_64-pc-linux-gnu -emit-obj --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.cpp -mrelocation-model pic -pic-level 1 -fhalf-no-semantic-interposition -mframe-pointer=none -fdenormal-fp-math-f32=preserve-sign,preserve-sign -fno-rounding-math -aux-target-cpu x86-64 -mlink-builtin-bitcode /tmp/libbc-clang_rt.builtins-x86_64-amdgcn-gfx803-0aa211.a -fcuda-is-device -mllvm -amdgpu-internalize-symbols -fcuda-allow-variadic-functions -fvisibility hidden -fapply-global-visibility-to-externs -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/hip.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/ocml.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/ockl.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_daz_opt_on.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_unsafe_math_off.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_finite_only_off.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_correctly_rounded_sqrt_on.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_wavefrontsize64_on.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_isa_version_803.bc -target-cpu gfx803 -fno-split-dwarf-inlining -debugger-tuning=gdb -v -resource-dir /opt/rocm/llvm/lib/clang/13.0.0 -internal-isystem /opt/rocm/llvm/lib/clang/13.0.0/include/cuda_wrappers -internal-isystem /opt/rocm/include -include __clang_hip_runtime_wrapper.h -isystem /opt/rocm/llvm/lib/clang/13.0.0/include/.. -isystem /opt/rocm/hsa/include -isystem /opt/rocm/hip/include -internal-isystem /usr/local/include -internal-isystem /opt/rocm/llvm/lib/clang/13.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -internal-isystem /usr/local/include -internal-isystem /opt/rocm/llvm/lib/clang/13.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -std=c++11 -fdeprecated-macro -fno-autolink -fdebug-compilation-dir=/home/dmaylarov/bin/tryrust -ferror-limit 19 -fhip-new-launch-api -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -vectorize-loops -vectorize-slp -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -cuid=51ca7470219e73cf -fcuda-allow-variadic-functions -munsafe-fp-atomics -faddrsig -o /tmp/test-gfx803-b8358a.o -x hip test.cpp
clang -cc1 version 13.0.0 based upon LLVM 13.0.0git default target x86_64-pc-linux-gnu
ignoring nonexistent directory "/include"
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/opt/rocm/llvm/lib/clang/13.0.0/include"
ignoring duplicate directory "/usr/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/opt/rocm/llvm/lib/clang/13.0.0/include"
ignoring duplicate directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/rocm/llvm/lib/clang/13.0.0/include/..
 /opt/rocm/hsa/include
 /opt/rocm/hip/include
 /opt/rocm/llvm/lib/clang/13.0.0/include/cuda_wrappers
 /opt/rocm/include
 /usr/local/include
 /opt/rocm/llvm/lib/clang/13.0.0/include
 /usr/include
End of search list.
In file included from <built-in>:1:
/opt/rocm/hip/include/__clang_hip_runtime_wrapper.h:32:10: fatal error: 'cmath' file not found
#include <cmath>
         ^~~~~~~
1 error generated when compiling for gfx803.
```

**Comment by malcolmroberts** [comment]
You may just need g++12 as a dependency.

**Comment by Tianyang-Zhang** [comment]
Same here on Ubuntu 22:
```
root@ip-172-31-3-103:/home/tomz# hipcc -O2 -g -o ./test_app ./amd_test.cc -I/opt/rocm/include -L/opt/rocm/lib -L/opt/rocm/llvm/lib
In file included from <built-in>:1:
In file included from /opt/rocm-6.0.0/lib/llvm/lib/clang/17.0.0/include/__clang_hip_runtime_wrapper.h:50:
/opt/rocm-6.0.0/lib/llvm/lib/clang/17.0.0/include/cuda_wrappers/cmath:27:15: fatal error: 'cmath' file not found
#include_next <cmath>
              ^~~~~~~
1 error generated when compiling for gfx1011.
```

Any suggestions? Tried to re-install entire ROCm, and reinstall g++11 and clang but no luck.

**Comment by malcolmroberts** [comment]
If you installed via apt in Ubuntu 22, you need to pin the radeon repo so that it's selected instead of the main Ubuntu repos: https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/native-install/ubuntu.html

And for the cmath error, try installing `libstdc++-12-dev` via apt.

**Comment by Tianyang-Zhang** [comment]
installing `libstdc++-12-dev` via apt works for me! Thanks for helping!

**Comment by FeepingCreature** [comment]
If that doesn't work on 23.04, you may need `libstdc++-13-dev`.
