### ISSUE TITLE
[Issue]: HIP RTC Win11 gfx1100 causes invalid memory access SEH error, hiprtc0604.dll used

### ISSUE THREAD

**Issue by Tritonn204** [ROCm-Developer-Tools/HIP#3880]
### Problem Description

I cannot get hipRTC to work on Windows. 

When running the function for even a simple program below (compiled with hipcc):
```
#include <cstdio>
#include <stdexcept>

#ifdef _WIN32
#include <windows.h>
#endif

#ifdef TNN_HIP
#include <hip/hiprtc.h>
#include <hip/hip_runtime.h>
#endif

extern "C" void test_hiprtc_isolation() {
    printf("\n");
    printf("========================================\n");
    printf("[ISOLATION TEST] Starting HIPRTC isolation test\n");
    printf("[ISOLATION TEST] This runs BEFORE any other GPU initialization\n");
#ifdef _WIN32
    printf("[ISOLATION TEST] Thread ID: %lu\n", (unsigned long)GetCurrentThreadId());
    printf("[ISOLATION TEST] Process ID: %lu\n", (unsigned long)GetCurrentProcessId());
#endif
    printf("========================================\n");
    fflush(stdout);

#ifdef TNN_HIP
    printf("[ISOLATION TEST] Step 1: Checking HIP runtime initialization\n");
    fflush(stdout);

    // First, check if HIP runtime is accessible
    int deviceCount = 0;
    hipError_t hip_err = hipGetDeviceCount(&deviceCount);
    printf("[ISOLATION TEST] hipGetDeviceCount returned: %d (error code: %d)\n", deviceCount, hip_err);
    if (hip_err != hipSuccess) {
        printf("[ISOLATION TEST] WARNING: HIP runtime not initialized properly\n");
        fflush(stdout);
        return;
    }
    printf("[ISOLATION TEST] Found %d HIP device(s)\n", deviceCount);
    fflush(stdout);

    // Minimal test kernel - absolutely no includes or dependencies
    static constexpr auto test_kernel {
    R"(
        extern "C"
        __global__ void minimal_test_kernel(float* output, float* input1, float* input2, int size) {
          int i = threadIdx.x + blockIdx.x * blockDim.x;
          if (i < size) {
            output[i] = input1[i] + input2[i];
          }
        }
    )"};

    printf("[ISOLATION TEST] Step 2: Creating HIPRTC program\n");
    printf("[ISOLATION TEST] Kernel source length: %zu bytes\n", sizeof(test_kernel));
    fflush(stdout);

    hiprtcProgram prog;
    hiprtcResult rtc_result;

#ifdef _WIN32
    // Use SEH to catch any crashes
    __try {
        printf("[ISOLATION TEST] Step 2a: Calling hiprtcCreateProgram (with SEH protection)...\n");
        fflush(stdout);

        rtc_result = hiprtcCreateProgram(
            &prog,
            test_kernel,
            "isolation_test.hip",
            0,           // No headers
            nullptr,     // No header sources
            nullptr      // No header names
        );

        printf("[ISOLATION TEST] Step 2b: hiprtcCreateProgram returned successfully\n");
        printf("[ISOLATION TEST] Return code: %d\n", rtc_result);
        fflush(stdout);
    }
    __except(EXCEPTION_EXECUTE_HANDLER) {
        DWORD exceptionCode = GetExceptionCode();
        printf("\n");
        printf("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
        printf("[ISOLATION TEST] CRASH DETECTED in hiprtcCreateProgram!\n");
        printf("[ISOLATION TEST] Exception code: 0x%08X\n", exceptionCode);

        // Decode common exception codes
        switch(exceptionCode) {
            case EXCEPTION_ACCESS_VIOLATION:
                printf("[ISOLATION TEST] Exception type: EXCEPTION_ACCESS_VIOLATION (memory access error)\n");
                break;
            case EXCEPTION_ARRAY_BOUNDS_EXCEEDED:
                printf("[ISOLATION TEST] Exception type: EXCEPTION_ARRAY_BOUNDS_EXCEEDED\n");
                break;
            case EXCEPTION_DATATYPE_MISALIGNMENT:
                printf("[ISOLATION TEST] Exception type: EXCEPTION_DATATYPE_MISALIGNMENT\n");
                break;
            case EXCEPTION_STACK_OVERFLOW:
                printf("[ISOLATION TEST] Exception type: EXCEPTION_STACK_OVERFLOW\n");
                break;
            default:
                printf("[ISOLATION TEST] Exception type: Unknown/Other\n");
                break;
        }

        printf("[ISOLATION TEST] Context: Running in ISOLATED environment on main thread\n");
        printf("[ISOLATION TEST] This confirms the crash is FROM hiprtc itself, NOT interference\n");
        printf("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
        fflush(stdout);

        throw std::runtime_error("hiprtcCreateProgram crashed in isolation test");
    }
#else
    printf("[ISOLATION TEST] Step 2a: Calling hiprtcCreateProgram (no SEH on this platform)...\n");
    fflush(stdout);

    rtc_result = hiprtcCreateProgram(
        &prog,
        test_kernel,
        "isolation_test.hip",
        0,
        nullptr,
        nullptr
    );

    printf("[ISOLATION TEST] Step 2b: hiprtcCreateProgram returned successfully\n");
    printf("[ISOLATION TEST] Return code: %d\n", rtc_result);
    fflush(stdout);
#endif

    if (rtc_result != HIPRTC_SUCCESS) {
        printf("[ISOLATION TEST] ERROR: hiprtcCreateProgram failed with code %d\n", rtc_result);
        fflush(stdout);
        return;
    }

    printf("[ISOLATION TEST] Step 3: Compiling HIPRTC program\n");
    fflush(stdout);

#ifdef _WIN32
    __try {
        printf("[ISOLATION TEST] Step 3a: Calling hiprtcCompileProgram (with SEH protection)...\n");
        fflush(stdout);

        // Simple compilation options
        const char* options[] = {"-O2"};
        rtc_result = hiprtcCompileProgram(prog, 1, options);

        printf("[ISOLATION TEST] Step 3b: hiprtcCompileProgram returned successfully\n");
        printf("[ISOLATION TEST] Return code: %d\n", rtc_result);
        fflush(stdout);
    }
    __except(EXCEPTION_EXECUTE_HANDLER) {
        DWORD exceptionCode = GetExceptionCode();
        printf("\n");
        printf("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
        printf("[ISOLATION TEST] CRASH DETECTED in hiprtcCompileProgram!\n");
        printf("[ISOLATION TEST] Exception code: 0x%08X\n", exceptionCode);

        switch(exceptionCode) {
            case EXCEPTION_ACCESS_VIOLATION:
                printf("[ISOLATION TEST] Exception type: EXCEPTION_ACCESS_VIOLATION\n");
                break;
            case EXCEPTION_STACK_OVERFLOW:
                printf("[ISOLATION TEST] Exception type: EXCEPTION_STACK_OVERFLOW\n");
                break;
            default:
                printf("[ISOLATION TEST] Exception type: Other (0x%08X)\n", exceptionCode);
                break;
        }

        printf("[ISOLATION TEST] Context: ISOLATED test on main thread during compilation\n");
        printf("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
        fflush(stdout);

        hiprtcDestroyProgram(&prog);
        throw std::runtime_error("hiprtcCompileProgram crashed in isolation test");
    }
#else
    printf("[ISOLATION TEST] Step 3a: Calling hiprtcCompileProgram...\n");
    fflush(stdout);

    const char* options[] = {"-O2"};
    rtc_result = hiprtcCompileProgram(prog, 1, options);

    printf("[ISOLATION TEST] Step 3b: hiprtcCompileProgram returned\n");
    printf("[ISOLATION TEST] Return code: %d\n", rtc_result);
    fflush(stdout);
#endif

    if (rtc_result != HIPRTC_SUCCESS) {
        printf("[ISOLATION TEST] Compilation failed, retrieving log...\n");
        fflush(stdout);

        size_t log_size = 0;
        hiprtcGetProgramLogSize(prog, &log_size);

        if (log_size > 0) {
            char* log = new char[log_size];
            hiprtcGetProgramLog(prog, log);
            printf("[ISOLATION TEST] Compilation log:\n%s\n", log);
            delete[] log;
        }

        hiprtcDestroyProgram(&prog);
        printf("[ISOLATION TEST] ERROR: Compilation failed with code %d\n", rtc_result);
        fflush(stdout);
        return;
    }

    printf("[ISOLATION TEST] Step 4: Retrieving compiled code\n");
    fflush(stdout);

    size_t code_size = 0;
    hiprtcGetCodeSize(prog, &code_size);
    printf("[ISOLATION TEST] Compiled code size: %zu bytes\n", code_size);
    fflush(stdout);

    printf("[ISOLATION TEST] Step 5: Cleaning up\n");
    fflush(stdout);

    hiprtcDestroyProgram(&prog);

    printf("\n");
    printf("========================================\n");
    printf("[ISOLATION TEST] SUCCESS!\n");
    printf("[ISOLATION TEST] HIPRTC compilation works in isolation\n");
    printf("[ISOLATION TEST] If crashes occur later, they are from:\n");
    printf("[ISOLATION TEST]   - Thread interactions\n");
    printf("[ISOLATION TEST]   - Memory corruption from other code\n");
    printf("[ISOLATION TEST]   - Race conditions with GPU state\n");
    printf("========================================\n");
    printf("\n");
    fflush(stdout);

#else
    printf("[ISOLATION TEST] TNN_HIP not defined, skipping test\n");
    fflush(stdout);
#endif
}

// Simple entry point that just runs the isolation test.
int main() {
    try {
        test_hiprtc_isolation();
    } catch (const std::exception& e) {
        fprintf(stderr, "[ISOLATION TEST] EXCEPTION: %s\n", e.what());
        return 1;
    }
    return 0;
}
```

The output is this:
```
========================================
[ISOLATION TEST] Starting HIPRTC isolation test
[ISOLATION TEST] This runs BEFORE any other GPU initialization
[ISOLATION TEST] Thread ID: 23028
[ISOLATION TEST] Process ID: 38584
========================================
[ISOLATION TEST] Step 1: Checking HIP runtime initialization
[ISOLATION TEST] hipGetDeviceCount returned: 1 (error code: 0)
[ISOLATION TEST] Found 1 HIP device(s)
[ISOLATION TEST] Step 2: Creating HIPRTC program
[ISOLATION TEST] Kernel source length: 8 bytes
[ISOLATION TEST] Step 2a: Calling hiprtcCreateProgram (with SEH protection)...

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[ISOLATION TEST] CRASH DETECTED in hiprtcCreateProgram!
[ISOLATION TEST] Exception code: 0xC0000005
[ISOLATION TEST] Exception type: EXCEPTION_ACCESS_VIOLATION (memory access error)
[ISOLATION TEST] Context: Running in ISOLATED environment on main thread
[ISOLATION TEST] This confirms the crash is FROM hiprtc itself, NOT interference
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[ISOLATION TEST] EXCEPTION: hiprtcCreateProgram crashed in isolation test
```

I've tried swapping the DLL for an older one (hiprtc0601.dll), and also running the program on my other Windows Machine that has an RX 6600XT w/ no HIP install. Exact same result, indicating there is something going awry with the self-contained hipRTC functionality.

Is this an issue with architecture support, or does this reprod sequence indicate a bug? I am writing a JIT-enabled program where the same setup works fine for Linux/WSL.

### Operating System

Windows 11: 10.0.22631

### CPU

AMD Ryzen 7 5800X 8-Core Processor

### GPU

AMD Radeon RX 7900 XTX

### ROCm Version

6.4.50101-9a6572ae7

### Steps to Reproduce

- Install ROCm 6.4 for Windows
- Run `hipconfig`
- Make a new folder somewhere safe for demo code
- Place the code from the description there as `test_hiprtc_isolation.cpp`
- Create a CMakeLists.txt in the same directory as the code from the issue description above, with these contents:
```
cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED ENV{HIP_PATH})
  message(FATAL_ERROR "HIP_PATH environment variable must be set (e.g. C:/Program Files/AMD/ROCm/6.4)")
endif()

set(HIP_CLANG_BIN "$ENV{HIP_PATH}/bin")

set(CMAKE_C_COMPILER   "${HIP_CLANG_BIN}/clang.exe"   CACHE FILEPATH "ROCm hip-clang C compiler"   FORCE)
set(CMAKE_CXX_COMPILER "${HIP_CLANG_BIN}/clang++.exe" CACHE FILEPATH "ROCm hip-clang C++ compiler" FORCE)

project(hiprtc_isolation_test LANGUAGES C CXX)

if(DEFINED ENV{HIP_PLATFORM})
  set(HIP_PLATFORM "$ENV{HIP_PLATFORM}")
else()
  message(FATAL_ERROR
    "HIP_PLATFORM environment variable is not set. "
    "Set it to 'amd' or 'nvidia' before configuring."
  )
endif()

string(TOLOWER "${HIP_PLATFORM}" HIP_PLATFORM_LOWER)
message(STATUS "HIP_PLATFORM=${HIP_PLATFORM_LOWER}")

find_path(HIP_INCLUDE_DIR hip/hip_runtime.h
  HINTS "$ENV{HIP_PATH}/include"
)

find_library(HIPRTC_LIBRARY hiprtc
  HINTS "$ENV{HIP_PATH}/lib" "$ENV{HIP_PATH}/lib64"
)

find_library(HIP_RUNTIME_LIBRARY amdhip64
  HINTS "$ENV{HIP_PATH}/lib" "$ENV{HIP_PATH}/lib64"
)

add_executable(hiprtc_isolation test_hiprtc_isolation.cpp)

target_include_directories(hiprtc_isolation PRIVATE ${HIP_INCLUDE_DIR})

target_link_libraries(hiprtc_isolation PRIVATE
  ${HIPRTC_LIBRARY}
  ${HIP_RUNTIME_LIBRARY}
)

target_compile_definitions(hiprtc_isolation PRIVATE TNN_HIP)

if(HIP_PLATFORM_LOWER STREQUAL "amd")
  target_compile_definitions(hiprtc_isolation
    PRIVATE
      __HIP_PLATFORM_AMD__=1
  )
elseif(HIP_PLATFORM_LOWER STREQUAL "nvidia")
  target_compile_definitions(hiprtc_isolation
    PRIVATE
      __HIP_PLATFORM_NVIDIA__=1
  )
else()
  message(FATAL_ERROR
    "Unknown HIP_PLATFORM='${HIP_PLATFORM}'. "
    "Expected 'amd' or 'nvidia'."
  )
endif()

if (WIN32)
    get_filename_component(_hiprtc_libdir      "${HIPRTC_LIBRARY}" DIRECTORY)
    get_filename_component(_hiprtc_libname_we  "${HIPRTC_LIBRARY}" NAME_WE)

    get_filename_component(_hiprtc_rocm_root   "${_hiprtc_libdir}/.." ABSOLUTE)
    set(_hiprtc_bindir "${_hiprtc_rocm_root}/bin")

    file(GLOB _hiprtc_dlls "${_hiprtc_bindir}/${_hiprtc_libname_we}*.dll")

    if (NOT _hiprtc_dlls)
        message(WARNING "No HIPRTC DLLs found matching ${_hiprtc_bindir}/${_hiprtc_libname_we}*.dll")
    else()
        message(STATUS "HIPRTC DLLs to copy: ${_hiprtc_dlls}")
    endif()

    get_filename_component(_hiprt_libdir      "${HIP_RUNTIME_LIBRARY}" DIRECTORY)
    get_filename_component(_hiprt_libname_we  "${HIP_RUNTIME_LIBRARY}" NAME_WE)

    get_filename_component(_hiprt_rocm_root   "${_hiprt_libdir}/.." ABSOLUTE)
    set(_hiprt_bindir "${_hiprt_rocm_root}/bin")

    file(GLOB _hiprt_dlls "${_hiprt_bindir}/${_hiprt_libname_we}*.dll")

    if (NOT _hiprt_dlls)
        message(WARNING "No HIP runtime DLLs found matching ${_hiprt_bindir}/${_hiprt_libname_we}*.dll")
    else()
        message(STATUS "HIP runtime DLLs to copy: ${_hiprt_dlls}")
    endif()

    add_custom_command(
        TARGET hiprtc_isolation POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different
            ${_hiprtc_dlls}
            ${_hiprt_dlls}
            $<TARGET_FILE_DIR:hiprtc_isolation>
    )
endif()
```
- Generate it with `cmake -S . -B build -G "Ninja"` in cmd
- Run `cmake --build build --config Release`
- Run the executable now in the build directory

### Additional Information

GDB output:
```
[ISOLATION TEST] Step 2a: Calling hiprtcCreateProgram (with SEH protection)...

Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) where
#0  0x0000000000000000 in ?? ()
#1  0x00007ffa19768378 in hiprtcVersion () from F:\git\Tnn-miner\hiprtc_standalone_test\build\hiprtc0604.dll
#2  0x00007ffa19767506 in hiprtcVersion () from F:\git\Tnn-miner\hiprtc_standalone_test\build\hiprtc0604.dll
#3  0x00007ffa19753245 in hiprtcCreateProgram () from F:\git\Tnn-miner\hiprtc_standalone_test\build\hiprtc0604.dll
#4  0x00007ff68bcf11d2 in ?? ()
#5  0x00007ff68bcf174e in ?? ()
#6  0x00007ff68bcf2199 in ?? ()
#7  0x00007ff68bcf22d2 in ?? ()
#8  0x00007ff68bcf235e in ?? ()
#9  0x00007ff68bcf237e in ?? ()
#10 0x00007ffb5b98259d in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\System32\kernel32.dll
#11 0x00007ffb5d2caf78 in ntdll!RtlUserThreadStart () from C:\WINDOWS\SYSTEM32\ntdll.dll
#12 0x0000000000000000 in ?? ()
```
